### ISSUE TITLE
example Cannot convert "[object Promise]" to unsigned long

### ISSUE THREAD

**Issue by lang795** [ZettaScaleLabs/zenoh-typescript#1]
![screenshot-20240513-212427](https://github.com/ZettaScaleLabs/zenoh-ts/assets/50796456/1b387848-677d-4463-b30d-e0ba5bd3179b)

Am I missing a step?

**Comment by Benv547** [comment]
I have the same problem here. The word "async" seems to be missing around line 7086 on **esm/wasm/zenoh-wasm.js**.
But it's a modification of a generated file and I don't see how to fix it on "source" files.
```
if (isUnsignedType) {
  toWireType = async function(destructors, value) {
   checkAssertions(value, this.name);
   return value >>> 0;
  };
 } else {
  toWireType = async function(destructors, value) {
   checkAssertions(value, this.name);
   return value;
  };
 }
```

**Comment by lang795** [comment]
This is probably related to zenoh-pico, but also to the system environment, and I think the Example project needs some extra hints.

**Comment by Charles-Schleich** [comment]
Hello all,
The previous approach we were taking using Zenoh-pico -> WASM via Emscripten to expose Zenoh functionality in the Typescript has been abandoned. 
Reasons behind this decision : 
1. At the time of the decision Emscripten did not support secure websockets, a feature we needed in internal projects at Zettascale.
2. Difficulty in getting stable Async behavior with Zenoh-Pico and Emscripten and Javascript. 

We have instead opted for a Websocket based Remote-Api-Plugin approach which is currently being developed on the branch `feat/remote-api`. 
At the time of writing this is still in development.
